### ISSUE TITLE
MethodError for linear system x' = ax

### ISSUE THREAD

**Issue by mforets** [JuliaReach/MathematicalSystems.jl#141]
```julia
julia> a = 2.0
2.0

julia> @system(x' = ax)
ERROR: MethodError: no method matching LinearContinuousSystem(::Float64)
Closest candidates are:
  LinearContinuousSystem(::MT<:AbstractArray{T,2}) where {T, MT<:AbstractArray{T,2}} at /home/mforets/.julia/dev/MathematicalSystems/src/systems.jl:114
Stacktrace:
 [1] top-level scope at REPL[11]:1
```

**Comment by ueliwechsler** [comment]
I propose to fix this by adding the constructors
```julia
LinearContinuousSystem(A::Real) = LinearContinuousSystem([A][:,:])
LinearDiscreteSystem(A::Real) = LinearDiscreteSystem([A][:,:])
AffineDiscreteSystem(A::Real,B::Real) = AffineDiscreteSystem([A][:,:], [B])
AffineContinuousSystem(A::Real,B::Real) = AffineContinuousSystem([A][:,:], [B])
```
Later fixes the scalar example from #140.

**Comment by mforets** [comment]
Hmm i'm not convinced about this proposal. I would prefer to keep the constructor for systems to the bare minimum in this library. And the fact that `LinearContinuousSystem(A::Real)` creates a new matrix-based system is a bit counter-intuitive (i would expect that it creates a new system with a scalar field `A`, but we don't have that yet).

**Comment by ueliwechsler** [comment]
I try to phrase my thoughts differently. I would expect that for an affine system the state and input matrix is represented as a matrix type since this generalizes to arbitrary dimensions, also for the corner case with scalar values. And in this context, I would consider the constructor `AffineContinuousSystem(2,3)` or `@system(x' = 2x + 3)`  syntactic sugar for the matrix types `2*ones(1,1)` and `3*ones(1)`.

> (i would expect that it creates a new system with a scalar field `A`, but we don't have that yet).

Would this imply, that we create a new type for every existing type which only allows for scalar inputs?

**Comment by schillic** [comment]
I think that a 1D system should still consist of a matrix instead of a scalar. Otherwise the interface is inconsistent because your code may rely on getting an `AbstractMatrix` when calling `state_matrix(·)` etc. and the code would be type unstable.
If the need for 1D systems arises, we can still support them with new types (with a new constructor name to achieve type-stable code). But in this case you just want to improve the macro power, so I would rather use the current system types to achieve that.

However, the proposed implementation is not efficient in terms of allocations:

```julia
julia> A = 2.5;

julia> @time [A][:,:]
  0.000027 seconds (8 allocations: 400 bytes)
1×1 Array{Float64,2}:
 2.5

julia> @time M = Matrix{typeof(A)}(undef, 1, 1); M[1, 1] = A; M
  0.000029 seconds (5 allocations: 256 bytes)
1×1 Array{Float64,2}:
 2.5

julia> using BenchmarkTools

julia> @btime [$A][:,:]
  70.232 ns (2 allocations: 192 bytes)
1×1 Array{Float64,2}:
 2.5

julia> @btime (M = Matrix{typeof($A)}(undef, 1, 1); M[1, 1] = $A; M)
  33.004 ns (1 allocation: 96 bytes)
1×1 Array{Float64,2}:
 2.5
```

**Comment by ueliwechsler** [comment]
> Hmm i'm not convinced about this proposal.

Is the explanation and the more efficient implementation from @schillic more convincing? 😉
Or in other words, would you accept a PR of this implementation? (it would add one additional constructor to every system with at least one matrix fields)

**Comment by mforets** [comment]
> Or in other words, would you accept a PR of this implementation?
> (it would add one additional constructor to every system with at least one matrix fields)

Ok!!

**Comment by ueliwechsler** [comment]
😁
