### ISSUE TITLE
IVP macro with system

### ISSUE THREAD

**Issue by mforets** [JuliaReach/MathematicalSystems.jl#199]
```julia
S = @system(x'=-x)
@ivp(S, x(0) ∈ X0)
```

idea:

```julia
macro ivp(expr...)
    try
        if isa(expr, Tuple{Symbol, Expr}) # handle @ivp(S::AbstractSystem, x(0) ∈ X0)
            T = ... # get type of expr[1]
            if isa(T, AbstractSystem)
                sys = expr[1]
                @capture(expr[2], x_(0) ∈ x0_) || throw(ArgumentError("malformed epxpression")) # TODO handle equality
                ivp = Expr(:call, InitialValueProblem, :($(expr[1])), :($x0))
                return esc(ivp)
            else
                error("...")
            end
        end
        dyn_eq, AT, constr, state, input, noise, dim, x0 = _parse_system(expr)
.....
```

**Comment by ueliwechsler** [comment]
This idea looks good to me. Is there anything missing for it to work?

**Comment by mforets** [comment]
my "idea" doesn't quite work if you try it. i think that the problem was how to check for the system type inside the macro. if you know how to fix it that would be great :)

**Comment by ueliwechsler** [comment]
I will try to have a look this week.

**Comment by ueliwechsler** [comment]
I think I have a working solution.  It is in a new branch (see below). I looking forward to your feedback.

I had to change the condition for checking if a system is used as an argument. Because as far as I know, we cannot directly extract the type of the arguments without using `eval` and even with `eval` I am not sure how to do it.

What I tried is checking the first input argument for its structure in the  `parses_as_system` function. If it is captured by `@system(args_)` it is a `AbstractSystem` and if it is not captured by `a_ = b_` is is not an dynamic equation and we assume it is an `AbstractSystem` contained in a variable. 

https://github.com/JuliaReach/MathematicalSystems.jl/blob/1709d3f90bf73f195a53d4f49e39dccebd2bfa0a/src/macros.jl#L931-L971

**Comment by mforets** [comment]
Good!! I tried that branch and first checked that existing tests pass :heavy_check_mark:  Then, as you said all of these are parsed correctly:

```julia
julia> using Revise, MathematicalSystems

julia> @ivp(@system(x' = rand(2, 2) * x), x(0) ∈ rand(2))
InitialValueProblem{LinearContinuousSystem{Float64,Array{Float64,2}},Array{Float64,1}}(LinearContinuousSystem{Float64,Array{Float64,2}}([0.43205636256
38514 0.6149903963087375; 0.07363462843400392 0.2828424205768685]), [0.33277913276746696, 0.3014580867149783])

julia> s = @system(x' = rand(2, 2) * x)
LinearContinuousSystem{Float64,Array{Float64,2}}([0.15070386134981661 0.777603543660554; 0.6332790575613105 0.4823847796992149])

julia> @ivp(s, x(0) ∈ rand(2))
InitialValueProblem{LinearContinuousSystem{Float64,Array{Float64,2}},Array{Float64,1}}(LinearContinuousSystem{Float64,Array{Float64,2}}([0.15070386134
981661 0.777603543660554; 0.6332790575613105 0.4823847796992149]), [0.056586191833263744, 0.8251400864923675])
```

Can we have a PR that includes those tests?

**Comment by ueliwechsler** [comment]
Sure, I make a PR with my branch.  This tests should already be included.
